### ISSUE TITLE
research background tasks

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/CSHR#14]
should be used for mailing 

- https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxii-background-jobs
- https://python-rq.org
- https://docs.celeryq.dev/en/stable/getting-started/introduction.html

**Comment by Mahmoud-Emad** [comment]
all background tasks implemented with celery by @mhmdhelmy28 and @andrew-nassef
