### ISSUE TITLE
edit a request that have been already approved or rejected

### ISSUE THREAD

**Issue by 0oM4R** [codescalersinternships/CSHR#148]
As mentioned in #4 the supervisor  should be apple to edit request, so this should be added to the frontend.

> Suggestion : add edit button beside the view button that enable the opposite button only and hide the old one. 

 
![Screenshot from 2022-09-15 16-08-34](https://user-images.githubusercontent.com/62248851/190425837-cebaaca3-e1fb-4e2f-b8bc-2a06012bb92e.png)

**Comment by Mahmoud-Emad** [comment]
@omar-sherif9992 
You can continue @0oM4R work
