### ISSUE TITLE
Can not create a new user 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#182]
After entering all the data and clicking submit nothing happens 
<img width="1106" alt="Screen Shot 2022-10-27 at 9 57 22 AM" src="https://user-images.githubusercontent.com/14869003/198273491-b30ad57c-0048-49eb-ae3d-8a54585cd35a.png">

**Comment by Mahmoud-Emad** [comment]
Hello Nayer,
are you sure you entered all fields? also, is the submit button disabled or enabled?
Thank you.

**Comment by Nayer-Sobhy** [comment]
I'm sure all the fields were filled properly.
it was enabled but nothing happens when I click on it
