### ISSUE TITLE
Home screen view

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#185]
can we reduce the size of the left part of the screen so the right calendar is fully viewed 
<img width="1354" alt="Screen Shot 2022-10-26 at 1 51 15 PM" src="https://user-images.githubusercontent.com/14869003/198274068-9abd6b22-e09a-4030-8eee-147a6d0b11fb.png">

**Comment by Mahmoud-Emad** [comment]
@Nayer-Sobhy 
Can you tell me what is your screen size, also you sure you are not on zoom mode!

**Comment by Nayer-Sobhy** [comment]
14inch
Not zoom mode
Google chrome
