### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by rkhamis** [codescalersinternships/CSHR#2]
Each user should have a profile. This profile will have some public and some screened information.
 - Public information visible to the entire organization:
    - [x]  Full name
    - [x]  Picture Photo
    - [x]  DOB
    - [x]  Telegram
    - [x]  email address
    - [x]  Joining date 
    - [x] Location (which office)
    - [x] Reporting to 
    - [x] Skills, trainings and courses achieved and link to certificates (if available)

    

 - Information visible to supervisor and admin and user:
    - [x] Mobile number
    - [x] checklist of provided official docs (@nayer-sobhy to provide the checklist)
    - [ ] End of probation period (a link to the evaluation form)
    - [x] Social insurance number
    - [x] Team (Dev-QA-Ops-Marketing-Management-Accounting)
    - [x] Annual balances remaining (Annuals-emergencies-excuses and public)
    - [x] Company properties that have been given to (laptop, bag, screen, sim card,....
    - [x] Regular evaluation scores with links to evaluations

 - information visible only to Admin and user:
    - [x] Benefits 
    - [x] Net Salary before joining (optional)
    - [x] Joining Salary (optional)
    - [x] Current Salary NET
    - [x] Current Salary GROSS

**Comment by Mahmoud-Emad** [comment]
as I understand the evaluation links will be global as `peer 2 peer form` or `reverse form`, e.g. Mahmoud, Reem, and Thabet will request the same link and it depends on the request user email, so how we can set the score to an exacting user? also the link to his evaluation?? is this will provided by the admin or supervisor?

**Comment by rkhamis** [comment]
the evaluations each user sees in their profile is the the one by their team lead
this will be indeed provided by the admin/supervisor

links to the **forms** of peer to peer or reverse evalution can be added

**Comment by Mahmoud-Emad** [comment]
@aliasaddik 
implemented?
in case not yet, please update this issue.

**Comment by aliasaddik** [comment]
Regarding the backend :

- Two endpoints ( get all users and get one specific user's info) are implemented for any logged-in user to view public information visible to the entire organization. 
- Two endpoints ( get all users and get one specific user's info) are implemented for any supervisor to view information visible to supervisor and admin and user along with all more general info.
-  Four endpoints ( get all users, get one specific user's info, update and delete a user) are implemented for any admin to view and edit information visible only to Admin and user along with all more general info.
-  Two endpoints (get my info and update some info) are implemented for any loggedin user to view and edit their own info.
- the fields a user can edit are  email, telegram username, birthday, social_insurance_number, mobile number.

**Comment by Mahmoud-Emad** [comment]
So I will close this issue as implemented!
