### ISSUE TITLE
remove/hide some of the option in the dash board page 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#205]
hide the( evaluation form, user evaluation form, user documents) from the dash board page 
<img width="1324" alt="Screenshot 2023-10-25 at 3 33 08 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/a503aa9e-022d-4eca-8536-b6b38f4fcb85">

**Comment by Mahmoud-Emad** [comment]
Should be done
