### ISSUE TITLE
Update the teams in the team drop down menu

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#207]
drop down menu should be:
Business Development
Development
HR & Finance
QA
Marketing
Operations
Support 
<img width="906" alt="Screenshot 2023-10-25 at 4 02 01 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/c6063cda-ea8e-4aa2-920e-29b3f3a1e25f">

**Comment by Mahmoud-Emad** [comment]
Should be done
