### ISSUE TITLE
Update the location drop down menu

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#208]
the drop down menu of the location in the add new user form
 should be:
Belgium 
Egypt
India
Mauritius 
UAE
Zanzi
<img width="936" alt="Screenshot 2023-10-25 at 4 07 15 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/97e9bb9a-cc31-49f0-9b79-490fbaf13ef1">

**Comment by Mahmoud-Emad** [comment]
Should be done
