### ISSUE TITLE
Remove/hide salary related info 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#209]
remove/hide the gross current salary, net current salary and add more salary from the add new user form 
<img width="895" alt="Screenshot 2023-10-25 at 4 10 40 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/b9481b28-6fa9-4e9a-8af4-41ca71466c94">

**Comment by Mahmoud-Emad** [comment]
Should be done
