### ISSUE TITLE
updating the update profile form from setting page 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#211]
Remove/Hide the salary part from the profile page 
<img width="1428" alt="Screenshot 2023-10-25 at 4 15 48 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/8dd1e910-8b7b-4e21-9cc4-63929fda2ee9">

**Comment by Mahmoud-Emad** [comment]
Should be done
