### ISSUE TITLE
changing the icon of the users from the menu 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#213]
Can we switch the icon of users with the icon of requests 
<img width="1434" alt="Screenshot 2023-10-26 at 11 25 02 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/967b14d0-b07b-454e-a13a-9a8688b81cdc">

**Comment by Mahmoud-Emad** [comment]
Should be done
