### ISSUE TITLE
Update the form "Update user Balance"

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#214]
Can we add the "name of the user" in the message instead of (this is the user balance.......) so it will be (this is the "name" balance.......)
Can we remove all the text.
Can we add location/office at the top of the form.
 
<img width="1437" alt="Screenshot 2023-10-26 at 11 28 48 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/5f1b80f2-741b-4a97-83e9-d8919cc6a23a">

**Comment by Mahmoud-Emad** [comment]
For the ' office admin feature' it needs to be done in the backend, I'm working in it.

**Comment by Mahmoud-Emad** [comment]
Should be done
