### ISSUE TITLE
Update the profile page from the admin view

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#215]
hide the salary section, the documents section, skills, certicates and the evaluation section 
update the balance view so it's increasing when I take vacations example: I start with 0/15 and if I take 3 days then the balance should be 3/15 and so on 

<img width="1437" alt="Screenshot 2023-10-26 at 11 34 33 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/8844b8fe-3177-4052-aacd-eba044d34b0b">

**Comment by Mahmoud-Emad** [comment]
This should be implemented
