### ISSUE TITLE
Birthday notification issue 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#227]
showing all users have a birthday and it's not on the correct day 
<img width="1440" alt="Screenshot 2023-11-06 at 10 03 15 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/cba20625-aeb8-4b9f-bbfa-b9680965e6a2">
<img width="1428" alt="Screenshot 2023-11-06 at 10 03 27 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/d03fca55-9df6-4742-8a16-d8622c9b7470">

**Comment by Mahmoud-Emad** [comment]
While we currently have placeholder data for nine users, it's noticeable that they share the same birthday, resulting in an unorganized display of their cards. Rest assured, this is temporary, and we plan to remove this dummy data upon publishing our first version. Once we have real user data, the issue of multiple users sharing the same birthday will be resolved.
