### ISSUE TITLE
updating/renaming item on the side menu 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#229]
Can we change "team" to "my team" and employees to "Threefold team"
<img width="1433" alt="Screenshot 2023-11-06 at 2 25 02 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/085314c4-e655-40d9-a3f4-a6ad16e25cb9">

**Comment by Mahmoud-Emad** [comment]
Should be done .
