### ISSUE TITLE
Hiding requests 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#230]
since there is no option to submit requests at this version can we please hide this page.
<img width="1427" alt="Screenshot 2023-11-06 at 2 25 59 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/4dadcafb-4d2e-47d9-b4b3-8a7339a9a715">

**Comment by Mahmoud-Emad** [comment]
Should be done.
