### ISSUE TITLE
Choosing vacation days

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#233]
can we make a drop down menu on the "Start Date" field and the"End Date" field so people can choose the days from this drop down instead of choosing on the small calendar above 
<img width="396" alt="Screenshot 2023-11-21 at 9 14 47 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/7c066107-f7f0-47b1-b7d7-f83a9e93e50e">

**Comment by Mahmoud-Emad** [comment]
Could you please explain to me how to select days from the drop-down?

**Comment by Nayer-Sobhy** [comment]
I mean if we click on date field a mini calendar appears and we can choose the date from, like the below 

![image](https://github.com/codescalersinternships/CSHR/assets/14869003/1a35355d-0611-40c1-b1f5-162a64451265)

**Comment by Mahmoud-Emad** [comment]
Do you mean the same one in the vacation balance values?

- ![image](https://github.com/codescalersinternships/CSHR/assets/57001890/cc6e9e95-aa86-4bae-8fb6-b4ec718819e4)

**Comment by Nayer-Sobhy** [comment]
Yeah exactly so when you click on the start date a small calendar appears and you can choose the start day from it

**Comment by Mahmoud-Emad** [comment]
Fair enough, okay let's do it so, also I found the same calendar as the one used in `Veda` for `svelte`, we can consider using it in the next version as well

Package and preview:
- https://github.com/YogliB/svelte-fullcalendar?ref=madewithsvelte.com 
- https://madewithsvelte.com/svelte-fullcalendar
