### ISSUE TITLE
Failure to update user profile

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#234]
When logged as admin and tried to update a user profile (change his birthday) I got an error message 
<img width="1351" alt="Screenshot 2023-11-21 at 9 27 01 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/4d9afe5e-7889-42ef-89db-d851c1645905">

**Comment by Mahmoud-Emad** [comment]
This might happen because the `Social insurance number` was empty, so we have to disable the submit button in case of any empty required input

**Comment by Mahmoud-Emad** [comment]
**Work Completed:**

The reported issue has been addressed successfully. To enhance data integrity, a validation rule has been implemented for all required input fields. This rule ensures rejection of null values, and the associated buttons have been disabled in cases where null values are detected.

![Validation Rule](https://github.com/codescalersinternships/CSHR/assets/57001890/4cd0b67d-0e8f-42a8-8651-40cae2eda918)
