### ISSUE TITLE
Admin account UI page

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#235]
Shouldn't the admin user have access to my team page as well. 
I can only find it in the normal user 
<img width="220" alt="Screenshot 2023-11-21 at 9 29 54 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/18f32cf7-d48f-4d57-a255-1bee3ee1d487">

**Comment by Mahmoud-Emad** [comment]
**Work Completed:**

The My Team page was initially designed to be visible only to normal users. The following updates have been implemented:

1. **Permission Adjustment:**
   - Removed the restriction on the My Team page view, enabling access for admins and supervisors.

2. **Filter Removal:**
   - Eliminated the "filter as user" feature in the team section.

3. **Table Resizing and Alerts:**
   - Adjusted table sizes for a more user-friendly display.
   - Introduced alerts to notify users when there are no team members or when no users are assigned as "reporting to."

4. **Department Field Addition:**
   - Enhanced the Department tables by adding an extra field, providing users with Department information directly on the screen.

![My Team Page](https://github.com/codescalersinternships/CSHR/assets/57001890/fd435f12-89c7-47f2-b032-46e762cb03b8)
