### ISSUE TITLE
Organizing Threefold Team page 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#236]
Can we group the users on the Threefold Team page according to their office and arrange them alphabetically
<img width="1435" alt="Screenshot 2023-11-21 at 9 31 45 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/6943ced7-8785-45a7-952c-801466f67cac">

**Comment by Mahmoud-Emad** [comment]
**Enhancement Proposal:**

We are considering implementing a feature that allows you to load only the team members working in the same country as the requested user. The idea is to include a drop-down select option with all available countries. Upon selecting a specific country, the system will dynamically load the team members associated with that country.

For example:

- If you select **Egypt**, the system will load all team members from Egypt.
- If you select **Belgium**, the system will load all team members from Belgium.

**Comment by Mahmoud-Emad** [comment]
**Work Completed:**

The ordered/organized feature has been successfully implemented. Now, the team is arranged based on the office, and the selected office upon loading the page becomes the user's office.

Here's the updated behavior:

1. Upon loading the `Threefold Team` page, the selected office corresponds to the user's office.
   - ![image](https://github.com/codescalersinternships/CSHR/assets/57001890/7efa20bf-83fd-4547-a7bb-6dc2bfdeef71)

2. When users click on the `Select Office` drop-down, only users from the selected office will be loaded. This allows users to switch offices and view the respective teams, as demonstrated in the screenshot.
   - ![image](https://github.com/codescalersinternships/CSHR/assets/57001890/472a3817-9282-4625-94e0-284d292d9b02)
