### ISSUE TITLE
Reporting to in the employee profile update page 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#240]
Can't find Nayer Admin in the reporting to when I was trying to update the Evon user 
<img width="2347" alt="Screen Shot 2023-11-27 at 1 44 07 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/55a644bd-59f0-4c50-b9e7-2250bc2a0dcf">

**Comment by Mahmoud-Emad** [comment]
Nayer is an admin user, while the `reporting-to` includes only team-leader users, who are a different user type.
