### ISSUE TITLE
Vacation appearance on the calendar 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#241]
I applied for a vacation from the 3rd to the 5th of Dec and it appeared on the calendar from the 3rd till the 6th 
<img width="2475" alt="Screen Shot 2023-11-28 at 9 21 15 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/8ffe4de8-6719-448d-b457-c9756216ef11">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
