### ISSUE TITLE
Telegram user name incorrect 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#243]
After creating the profile and adding the telegram username and saving the profile. The telegram that appears when I open the user profile is different. It should be @nayer_sobhy
<img width="847" alt="Screenshot 2023-12-14 at 10 24 13 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/c14473c5-0917-4add-b76f-d6752be13fc5">

**Comment by Mahmoud-Emad** [comment]
Should be done
Status: pending deployment

- ![image](https://github.com/codescalersinternships/CSHR/assets/57001890/6ad0c6c3-2d5b-43cd-8f05-7c1d58e9d576)
- ![image](https://github.com/codescalersinternships/CSHR/assets/57001890/a1e256bb-6947-4dcc-b516-6a8d51bb52ff)
- ![image](https://github.com/codescalersinternships/CSHR/assets/57001890/61da746d-a561-42c4-9cd6-f7474bcff02d)

**Comment by Nayer-Sobhy** [comment]
the link is redirecting to a new page with the user telegram wish is great but the 
issue is still there all telegram names showing only first name, so if I want just to copy and paste the name in my telegram it wont work

**Comment by zaelgohary** [comment]
Done in https://github.com/codescalers/CSHR/issues/272

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
