### ISSUE TITLE
error message when updating the vacation balance

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#244]
when updating the balance of a user. I get an error message but the balance actually gets updated 
<img width="1346" alt="Screenshot 2023-12-14 at 10 33 20 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/df4985f2-7f04-4daa-a52a-211a9a0894ee">

**Comment by Mahmoud-Emad** [comment]
Should be fixed now, will be deployed in the upcoming version
