### ISSUE TITLE
company properties 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#246]
Can we hide the company properties field in the creating new profile as it appears on the user profile page but there is no place to add the properties 
<img width="1356" alt="Screenshot 2023-12-14 at 11 08 13 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/ef709ec8-9310-478f-adce-844266ccb3f2">

**Comment by Mahmoud-Emad** [comment]
Should be Removed/Commented
