### ISSUE TITLE
Last name doesnt accept space

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#249]
when creating a new profile and trying to insert a last name consisting of more than a name it didnt accept
<img width="1356" alt="Screenshot 2023-12-18 at 1 46 38 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/657ed098-91aa-4280-ab9f-b1ce1663ab0f">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
