### ISSUE TITLE
multiple office 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#251]
is it possible to have a supervisor user with multiple office so he can approve vacations to people from different office. Like for example Azmy can we he be on Egypt office and Belgium office so he can approve vacations to his team from Cairo
<img width="1431" alt="Screenshot 2023-12-18 at 3 05 37 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/cae2a153-5a5a-4cc0-a40c-f5abe87f134f">

**Comment by Mahmoud-Emad** [comment]
The feature will be included in the upcoming milestone release.
