### ISSUE TITLE
Vacation appearance on the calendar 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#252]
When choosing vacation days it's not appearing right on the calendar it's showing one day less 
For example Rafik is off from 21 to 24 of December, the notification showing it correctly but on the calendar showing it till 23 only 
<img width="1377" alt="Screenshot 2023-12-18 at 3 05 04 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/4ff84abe-55e8-4640-8231-a37492f5038b">

**Comment by Nayer-Sobhy** [comment]
when tried with Evon it was displayed right and properly, so I'm not sure if the conflict because Rafik applied on vacation through the weekend or something else 
<img width="1433" alt="Screenshot 2023-12-18 at 3 22 37 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/c841fce1-d624-4d5e-b6f1-e2de6bb37b54">
<img width="817" alt="Screenshot 2023-12-18 at 3 22 46 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/90c25945-cb6d-426f-9ff5-7bfd76e2ccd5">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
