### ISSUE TITLE
people in the office display 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#253]
is it possible to display in the office alphabetically as now they are just sorted per the addition date 
<img width="1433" alt="Screenshot 2023-12-18 at 3 14 41 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/f4fa07f7-0a33-47c8-8803-a2b7dab1594e">

**Comment by zaelgohary** [comment]
Done.

![image](https://github.com/codescalers/CSHR/assets/40770501/4b685ef9-7a79-4be2-b6e6-8f56d1f82e48)

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
