### ISSUE TITLE
Birthdays is not displayed properly on the calendar 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#254]
when checking month of February 2024 it shows at the end of the page all birthdays next to each other 
<img width="1417" alt="Screenshot 2023-12-19 at 12 09 43 PM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/161da18d-e0c3-4101-9aff-38bdd780c46e">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
