### ISSUE TITLE
Vacation request by admin

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#255]
Can we please allow admin to apply for vacation for users in case they can't or not around a laptop 
<img width="1440" alt="Screenshot 2023-12-20 at 9 38 50 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/a38519e8-e93c-47d0-aaa5-639ad5358826">

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/codescalers/CSHR/pull/369 and https://github.com/codescalers/CSHR/pull/368

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
