### ISSUE TITLE
decimal balance

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#256]
The system give an error when trying to add a decimal number like 3.5
<img width="1370" alt="Screenshot 2023-12-20 at 9 43 43 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/7d0d35e9-cd74-4f6d-a70f-08983d290752">

**Comment by Mahmoud-Emad** [comment]
The feature will be included in the upcoming milestone release.
