### ISSUE TITLE
user name displayed on the vacation 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#257]
is it possible to display/show the name of the user on the vacation beside the vacation title in the calendar instead of having to open the vacation to see who is actually off, so for example in this screen shot: first vacation can be Rafik Magdy Vacation and the second one show Evon Yacoub vacation 

<img width="1437" alt="Screenshot 2023-12-20 at 9 57 53 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/47d4b225-46b9-4126-9a7c-de20445b8154">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
