### ISSUE TITLE
vacations are displayed on top of each other

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#258]
when someone applies for a vacation and some already applied for the dame dates it displays on top of each other not a stack. Can we please display them as rows. For example Evon applied from 25 to 27 and Ehab applied from 24 to 28  and this is how both are displayed as just one long vacation 
<img width="1434" alt="Screenshot 2023-12-20 at 10 08 02 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/40c883f7-31a3-4a17-88c1-c97cf143fe9a">

**Comment by 0oM4R** [comment]
the implementation of the calendar force sections to be in one row 

[Screencast from 20 ديس, 2023 EET 06:40:35 م.webm](https://github.com/codescalersinternships/CSHR/assets/62248851/f216d440-941d-4b8b-8615-8d4ad927af64)

even after add tooltip feature the overlapping has its effect

on the video, evon has a vacation from 26-31 including 28 but the section of 28 overlap on the original section

**Comment by zaelgohary** [comment]
Done in https://github.com/codescalers/CSHR/issues/265
