### ISSUE TITLE
Public holiday displays on the calendar

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#259]
Can we make sure that the public holiday displayed on the calendar shows which office is off 
<img width="1434" alt="Screenshot 2023-12-20 at 10 21 06 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/b494fa4e-e3d5-48af-a10c-a713bae21acb">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
