### ISSUE TITLE
the update/post vacation balance role

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#260]
when I add the balances on this page, shouldn't be reflected on the users of the office. Because when I added the values here the users balance did not change. Only the public holidays were added to the calendar 
<img width="1436" alt="Screenshot 2023-12-20 at 10 23 35 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/3b146fe6-bee7-4f4c-8da2-7e1f6a40e730">

**Comment by zaelgohary** [comment]
Done in https://github.com/codescalers/CSHR/issues/272

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
