### ISSUE TITLE
highlight the current day

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#261]
can we highlight the day we are currently in so people can instantly know which day it is. instead of checking the date and checking the calendar 
<img width="1431" alt="Screenshot 2023-12-20 at 11 41 27 AM" src="https://github.com/codescalersinternships/CSHR/assets/14869003/3d7d158b-36b1-46ce-be65-e02c7684b08c">

**Comment by zaelgohary** [comment]
Done in  https://github.com/codescalers/CSHR/issues/317

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
