### ISSUE TITLE
Implement Notifications Screen

### ISSUE THREAD

**Issue by Mahmoud-Emad** [codescalersinternships/CSHR#267]
### Description:
Develop a notifications screen, including the implementation of a toast for displaying notifications on time.

Please try to use [vue3-notifier](https://github.com/MohamedElmdary/vue3-notifier)

**Comment by zaelgohary** [comment]
WIP: 
Finished implementing the Notifications table and currently working on notification details.

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
