### ISSUE TITLE
Implement Vacation/Event/Meeting Details Screen

### ISSUE THREAD

**Issue by Mahmoud-Emad** [codescalersinternships/CSHR#268]
### Description:
 
Implement screens for vacation, event, and meeting details. Allow users to cancel vacation requests while pending approval. Users should also be able to delete requests for other modal types.

**Comment by zaelgohary** [comment]
@Mahmoud-Emad I got this error when I was trying to create a meeting.

![image](https://github.com/codescalers/CSHR/assets/40770501/28da129e-74e4-4698-b98d-17d417b92650)

Same error when creating an event also.

![image](https://github.com/codescalers/CSHR/assets/40770501/c8c16118-337a-448e-aec5-32a4e7f02f45)

Also, the Notifications API is not being updated. There is more than one pending vacation request and the API retrieves only one as shown below.

![image](https://github.com/codescalers/CSHR/assets/40770501/15e26692-501f-404c-9e45-4cdb125d36ec)


![image](https://github.com/codescalers/CSHR/assets/40770501/0c141394-d5db-451d-94e4-d47a35c88f6f)

P.S. I'm using an admin profile. Shouldn't it have access to all the features?

**Comment by zaelgohary** [comment]
Replaced with a dialogue for each event.
