### ISSUE TITLE
Implement Admin Dashboard with Forms

### ISSUE THREAD

**Issue by Mahmoud-Emad** [codescalersinternships/CSHR#272]
### Description: 

This issue involves creating an admin dashboard with various forms:
 - Update/Post Vacation Balance Form
 - Update Set User Vacation Balance Form
 - Vacation Balance Adjustment Form
 - Add New Office Form
 - Add New User Form (or integrate with Auth Issue)
 - Update User Information

**Comment by zaelgohary** [comment]
WIP:
Added dashboard layout, set vacations form & add office. However, the date picker in the form has a bug as it increments the dates without removing any of them if they duplicate.

**Comment by zaelgohary** [comment]
WIP:
All forms are implemented. However, I've faced an issue with update profile API as seen below. Also, added some styling and hints to the forms. There's one bug in the public holidays calendar, will look into it tomorrow.

![image](https://github.com/codescalers/CSHR/assets/40770501/257b1436-4367-4373-98e9-01a1e5c56ddf)

**Comment by zaelgohary** [comment]
Work Completed:
Worked on the following:
- Fix update user form
- vacations typo
- supervisor -> team lead
- update office vacation balance (hide and in the future allow multiple users)
- country -> autocomplete
- Social insurance shouldn't be required 
- in Zee superivsisor object Object
- the demo issues (date picker)
- Edit route guard to include admin only page (Dashboard)
- routes keeping logging you out

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
