### ISSUE TITLE
Go through The CSHR Application and see what needed as UI/UX

### ISSUE THREAD

**Issue by ehab-hassan** [codescalersinternships/CSHR#275]
- Change login design to match Codescaler Egypt themes.
- Add dropdown at profile picture at top right including profile and logout.
- Change all main buttons to the main blue color  3399CC.
- For admin users, we can add a button at the ThreeFold team so that the admin can add members here directly without going to the dashboard.
- Reorder icons at the sidebar I think the dashboard icons need to come after the Calendar.
- Some pages need more enhancement like alignment and size of font...
- Add light & dark mode (not priority I think)

**Comment by ehab-hassan** [comment]
for login
https://www.figma.com/proto/2UPe0LXnfiHYSq5HibsuEO/CSHR?type=design&node-id=1-2&t=JgiayFcO5Qxpt0Ox-0&scaling=scale-down&page-id=0%3A1

what u think guys if we change log to this

![cshr_small](https://github.com/codescalersinternships/CSHR/assets/10484295/ac67d7a6-cfd6-41b2-bc74-8eca0af69db7)


work still in progress
https://www.figma.com/file/2UPe0LXnfiHYSq5HibsuEO/CSHR?type=design&node-id=44-21&mode=design&t=t3hDZ1JizRp0IWa5-0

**Comment by zaelgohary** [comment]
As per my conversation with @ehab-hassan, the following pages are ready to be implemented:
- Login
- Profile
- Notifications
- Teams
- Users (Only the dropdown menu will be relocated)
- Settings (Button color will be changed)

**Comment by ehab-hassan** [comment]
Dashboard page updated at Figma also dark mode option
https://www.figma.com/file/2UPe0LXnfiHYSq5HibsuEO/CSHR?type=design&node-id=0-1&mode=design&t=BoEOYfK9YWMdkp1x-0

**Comment by ehab-hassan** [comment]
Nayer asked to change the login images to this 

![Login (2)](https://github.com/codescalers/CSHR/assets/10484295/3ea2dae1-637f-4d73-ac7e-171abb96a3ed)


![desktop 1](https://github.com/codescalers/CSHR/assets/10484295/e42a1c34-cc6d-4058-813c-86a17e80a3b9)

https://www.figma.com/file/2UPe0LXnfiHYSq5HibsuEO/CSHR?type=design&node-id=273-300&mode=design&t=TTgMy1vtmaWWjIgr-0


I separated the login issue here #293

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
