### ISSUE TITLE
Edit Calendar flow

### ISSUE THREAD

**Issue by zaelgohary** [codescalersinternships/CSHR#291]
In the current flow, the calendar shows all actions that would take place in the current month no matter the action state (approved, pending) or the account rule (signed in from a normal user and could see pending requests).

![image](https://github.com/codescalers/CSHR/assets/40770501/7a31abc6-d94b-4ef4-84eb-c6b3bafa3cc2)
![image](https://github.com/codescalers/CSHR/assets/40770501/33237675-0a14-418a-bf80-5d7e87fe974f)

Due to this, the administrator will not receive notifications for any added actions, requiring them to monitor the calendar throughout the day to identify any actions taken.

Proposed improvement:
- Send notifications to the admin for every action that requires approval, prompting them to approve or reject.
- The calendar should only display approved actions or actions that don't need approval.

**Comment by Nayer-Sobhy** [comment]
isn't it possible to have both options. 
the request to be shown on the calendar with the status pending approval and at the same time send notification 
to the appropriate approver ?
