### ISSUE TITLE
Update login page and make sure it responsive

### ISSUE THREAD

**Issue by ehab-hassan** [codescalersinternships/CSHR#293]
![Login (1)](https://github.com/codescalers/CSHR/assets/10484295/206dd5e8-8c98-4570-bc89-c155ce5c0069)

use this img

![desktop 1](https://github.com/codescalers/CSHR/assets/10484295/2900dd78-bbb4-431f-b5db-2cb91438b9ec)

**Comment by samaradel** [comment]
details added, just need some UI enhancement.
