### ISSUE TITLE
Tips and Questions and Enhancements for ui development_1.1

### ISSUE THREAD

**Issue by MohamedElmdary** [codescalersinternships/CSHR#299]
1. [x] Why did we use `createGlobalState` here? https://github.com/codescalers/CSHR/blob/development_1.1/client/src/store.ts#L1-L7
There is already a `useLocalStorage` doing the same job while syncing localstorage value so we don't need to initialize it here https://github.com/codescalers/CSHR/blob/development_1.1/client/src/App.vue#L30-L32.

2. [x] Please add error handling and loading state https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/LoginView.vue#L65-L73 (make sure to use async state from vueUse)

3. [x] Handle possible errors and loading state
https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/NotificationsView.vue#L146-L149

4. [x] Handle error https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/NotificationsView.vue#L162-L164

5. [ ] This `CustomDialog` override vuetify dialog so u don't need to import it just use `VDialog` instead https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/NotificationsView.vue#L15

6. [x] Handle Error https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/NotificationsView.vue#L166-L178

7. [x] Handle Error https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/ProfileView.vue#L53-L68

8. [x] Handle Error https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/SettingsView.vue#L43-L48

9. [x] Handle Error https://github.com/codescalers/CSHR/blob/development_1.1/client/src/views/TeamView.vue#L74-L78

10. [x] Emit event don't pass function https://github.com/codescalers/CSHR/blob/development_1.1/client/src/components/NotificationDetails.vue#L58-L61

11. [x] Use hooks in top level of component not inside function https://github.com/codescalers/CSHR/blob/development_1.1/client/src/components/SideDrawer.vue#L85

**Comment by MohamedElmdary** [comment]
- [x] Notification Dialog is not synced with query route
![image](https://github.com/codescalers/CSHR/assets/31689104/c29f0a5a-833a-48d3-9d4b-2383a1a646ee)
![image](https://github.com/codescalers/CSHR/assets/31689104/f418ffa9-ae38-4f71-83ce-71c3095f4a76)
![image](https://github.com/codescalers/CSHR/assets/31689104/964ec211-a3da-4c44-a0e2-8fe706d97ba1)

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
