### ISSUE TITLE
Vacations

### ISSUE THREAD

**Issue by rkhamis** [codescalersinternships/CSHR#3]
### Applying :

As a user I should be able to apply for any type (defined below) of vacation
I should be able to apply from either the calendar by selecting the day(s) or through a form
I should also be able to edit my request as long as it hasn't already been approved 
  
As a supervisor, I should be able to approve or deny a request. 
I should be able to edit a request that I have already approved
 - proposing: I should be able to see a changlelog

**The system should also automatically block the previous year balance after 21/3 of the current year**

### Balances:
as a user/supervisor, I should be able to see the remaining balance for each type of vacation

### Types of vacations:
   - Annual Leaves
   - Public Holidays
   - Emergency Leave
   - Leave Excuses ( = 0.25 day)

**Comment by Mahmoud-Emad** [comment]
@mhmdhelmy28 
Can you please update this issue and link the others issues?

**Comment by mhmdhelmy28** [comment]
1- https://github.com/codescalersinternships/CSHR/issues/113
2- https://github.com/codescalersinternships/CSHR/issues/114

**Comment by Mahmoud-Emad** [comment]
Closed as implemented!
