### ISSUE TITLE
After refreshing the profile page, all data appears as dashes.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [codescalersinternships/CSHR#300]
- ![image](https://github.com/codescalers/CSHR/assets/57001890/0dd77ed3-5895-4f6b-9366-447a483205c6)

- ![image](https://github.com/codescalers/CSHR/assets/57001890/f3c37b2a-ee2e-4a30-95e5-00a682693af6)

**Comment by maayarosama** [comment]
Upon refreshing, logged in user's data gets dismissed.

**Comment by zaelgohary** [comment]
Work completed:
Fixed assertUser error. However, found another issue when token expires. Will look into it tomorrow morning.
