### ISSUE TITLE
It is recommended to store the `access token` in `cookies` instead of `session storage`.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [codescalersinternships/CSHR#302]
Also please store the `refresh token`

- ![image](https://github.com/codescalers/CSHR/assets/57001890/724989b4-bcee-465a-8935-a1f368a350ef)

**Comment by zaelgohary** [comment]
Fixed in https://github.com/codescalers/CSHR/pull/295. added access token in local storage instead.
