### ISSUE TITLE
Enhancements of calender 

### ISSUE THREAD

**Issue by maayarosama** [codescalersinternships/CSHR#321]
- [x] Remove approval user field from vacation card
- [x] Discard the submit and cancel button in the vacation card, and make update button enabled when fields change
- [x] Remove expired chip from public holidays
- [ ] format date filed in vacation card
- [x] Display Actual days in vacation request card in an alert
- [x]  if the the actual days is zero display an alert to the user saying dates chosen might be weekends or public holidays and disable the apply button
- [x] Remove public holidays from v-select reasons in vacation request card
- [x] Add vacation balance to the v-select reasons in vacation request card

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
