### ISSUE TITLE
Threefold team enhancement 

### ISSUE THREAD

**Issue by ehab-hassan** [codescalersinternships/CSHR#326]
Enhace threefold team UI

**Comment by ehab-hassan** [comment]
working in progress
go through all and make all consistent 
![image](https://github.com/codescalers/CSHR/assets/10484295/84718398-0630-48c8-9f72-d70094dcc0a4)

**Comment by ehab-hassan** [comment]
Work Completed:
All done and PR merged to development_1.1
![image](https://github.com/codescalers/CSHR/assets/10484295/e9ce1edf-afe8-4bb6-ace8-df0a4a95e0e4)
![image](https://github.com/codescalers/CSHR/assets/10484295/821be675-4645-49bb-a2b4-e84314117518)
![image](https://github.com/codescalers/CSHR/assets/10484295/a23b7fed-3188-43c8-9b12-d3451ee0cfa7)
![image](https://github.com/codescalers/CSHR/assets/10484295/4191edd5-0ac0-4a8a-8c37-7eb101cbbad6)
![image](https://github.com/codescalers/CSHR/assets/10484295/c0888bbc-cb7c-4339-b7ec-96b0a0fca31f)
![image](https://github.com/codescalers/CSHR/assets/10484295/7a6177bc-852b-4e8b-9a7e-7cef8e5bd882)

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
