### ISSUE TITLE
Empty and reserved cells color-wired behavior

### ISSUE THREAD

**Issue by ehab-hassan** [codescalersinternships/CSHR#340]
Empty and reserved cells' color-wired behavior 
when I go to week and then back to month it shows otherwise all one color

https://github.com/codescalers/CSHR/assets/10484295/e35241bc-af05-4681-9020-2d69c342067b

**Comment by Mahmoud-Emad** [comment]
Not happening anymore. Please reopen the issue if you experience the same problem again.
