### ISSUE TITLE
Vacation balance not showing on users balance 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#341]
When adding the vacation balance, it's not added on the users 
<img width="1439" alt="Screenshot 2024-02-06 at 11 18 23 AM" src="https://github.com/codescalers/CSHR/assets/14869003/6b20d055-0a77-43d9-b6eb-90aac3752e4e">

**Comment by Mahmoud-Emad** [comment]
There was a bug un the deployed server and it fixed now

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
