### ISSUE TITLE
Can't change the date when applying on vacation from the calendar 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#342]
When I choose a date on the calendar and get the popup I can not change the to date 
<img width="801" alt="Screenshot 2024-02-06 at 11 15 59 AM" src="https://github.com/codescalers/CSHR/assets/14869003/6b56a118-2cdf-4575-91ae-bfbaed2670f6">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
