### ISSUE TITLE
Birthday popup 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#345]
The birthday popup employee details doesnt looks good 
I dont think we need the email may be the telegram name only instead of the details 
<img width="804" alt="Screenshot 2024-02-06 at 11 23 40 AM" src="https://github.com/codescalers/CSHR/assets/14869003/3a4e9f6c-f04c-4c05-8d9e-789d51af758b">

**Comment by Mahmoud-Emad** [comment]
## Issue update 

Updated 

![image](https://github.com/codescalers/CSHR/assets/57001890/29b94893-a65a-48e8-a5da-acfc3d770a93)

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
