### ISSUE TITLE
Admin accessibility  

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#346]
Can we please make sure that the admin can apply for vacation to users 
so for example I (as admin) can apply for  previous vacations to other users 
if we can add a drop down menu at the beginning (yourself, then the rest of the people in the office)
<img width="793" alt="Screenshot 2024-02-06 at 11 27 24 AM" src="https://github.com/codescalers/CSHR/assets/14869003/c05abb26-df6d-4b9d-a1f7-399668e28075">

**Comment by maayarosama** [comment]
In requesting vacation, in case the user logged in is an Admin
- Radio buttons were added to choose if the user will be requesting vacation for himself or another user
-  In case another user, a select field was added to list all the users in the same office as the admin
- Vacation balance in leave reason will be adjusted to the user selected
![Peek 2024-03-05 13-44](https://github.com/codescalers/CSHR/assets/66883096/177e3435-1f40-45a2-942c-6d0fe1e3850e)

**Comment by maayarosama** [comment]
Pr https://github.com/codescalers/CSHR/pull/367 drafted until https://github.com/codescalers/CSHR/pull/368 is merged

**Comment by Mahmoud-Emad** [comment]
Implemented in https://github.com/codescalers/CSHR/pull/367#pullrequestreview-1919328180
