### ISSUE TITLE
Not able to load all name from dropdown menu

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#361]
When trying to choose a user to update the vacation balance I only get limited user names 
<img width="1434" alt="Screenshot 2024-02-21 at 11 54 09 AM" src="https://github.com/codescalers/CSHR/assets/14869003/0664a4d0-0738-4c78-af47-db976c7e48a1">

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
