### ISSUE TITLE
vacation balance calculation issue when updating the balance

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#362]
When updating the vacation balance to an office the system leave the old balance as it is, so for example I made the annual leave 23 days then I set it again to 15 days and the balance for a user was 23/15 and my user was not updated 
<img width="1420" alt="Screenshot 2024-02-21 at 11 59 25 AM" src="https://github.com/codescalers/CSHR/assets/14869003/740c450b-6172-4fb3-be78-2e1a4e6dab26">
<img width="1420" alt="Screenshot 2024-02-21 at 12 02 04 PM" src="https://github.com/codescalers/CSHR/assets/14869003/9956fa6e-09db-43ee-8803-76b03d091bde">

**Comment by Mahmoud-Emad** [comment]
This issue should be reported in https://github.com/codescalers/CSHR/issues/364
