### ISSUE TITLE
spelling mistake in the public holiday message 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#372]
should be families 
<img width="1435" alt="Screenshot 2024-03-10 at 3 11 26 PM" src="https://github.com/codescalers/CSHR/assets/14869003/a175a22f-68e2-440d-ad81-ed19fa707c6a">

**Comment by Mahmoud-Emad** [comment]
Updated to `families`

**Comment by Mahmoud-Emad** [comment]
Closed as fixed, please if you notice that the issue still exists open it again.
