### ISSUE TITLE
Issue in filters

### ISSUE THREAD

**Issue by Mahmoud-Emad** [codescalersinternships/CSHR#375]
- When pressing on the `Birthday filter checkbox` the `Public Holidays Labels` disappear.

[Screencast from 03-17-2024 03:10:53 PM.webm](https://github.com/codescalers/CSHR/assets/57001890/4c30830b-11a4-4a7e-b4af-7b475f9f2fa1)

**Comment by maayarosama** [comment]
Duplicate of #353 , #376
