### ISSUE TITLE
Vacations are Shown as +1 on the calendar

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#379]
Days have only one or two vacations still it's not shown and shown as +1 more 
<img width="1420" alt="Screenshot 2024-03-25 at 10 17 55 AM" src="https://github.com/codescalers/CSHR/assets/14869003/7872307b-10f5-4012-b85f-d55cb54ffa38">

**Comment by Mahmoud-Emad** [comment]
I believe this issue should have been addressed in https://github.com/codescalers/CSHR/pull/384. If the problem persists, kindly re-open it again. It's worth noting that the FullCalendar package we utilize handles the requests, and when pressing on "+more," you'll observe the additional events displayed there.
