### ISSUE TITLE
Birthday changes when changing the joining date 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#383]
when I tried to change the joining date of Ehab the date of birth changed to today and it wont allow me to update the user

<img width="1227" alt="Screenshot 2024-03-26 at 10 48 01 AM" src="https://github.com/codescalers/CSHR/assets/14869003/1eb47f16-1483-4beb-8ce9-a1bf05ebc682">

**Comment by Mahmoud-Emad** [comment]
The issue could happen because of the binding on the `new Date()` contestant

**Comment by Mahmoud-Emad** [comment]
Should be fixed now
