### ISSUE TITLE
samar's telegram handle is email

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/CSHR#386]
![image](https://github.com/codescalers/CSHR/assets/64129/ce23fe6f-da5b-46aa-a94e-a691281e044a)

i wonder how that got added in the first place?

**Comment by Mahmoud-Emad** [comment]
We should kill this validation rule, we shouldn't give the telegram handle care whether that starts with `@` or not.

**Comment by ehab-hassan** [comment]
we need to change the Role also to Frontend Developer, not UI Designer

**Comment by maayarosama** [comment]
> we need to change the Role also to Frontend Developer, not UI Designer

The data presented locally and on the staging server are dummy data.

**Comment by Mahmoud-Emad** [comment]
> we need to change the Role also to Frontend Developer, not UI Designer

Please ping Nayer or Evon to do it

**Comment by Mahmoud-Emad** [comment]
Should be fixed
