### ISSUE TITLE
add leave excuses 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [codescalersinternships/CSHR#389]
can't set the time for the leave so taking a leave excuse for part of the day is not an option

**Comment by Mahmoud-Emad** [comment]
The leave excuse isn't there 

![image](https://github.com/codescalers/CSHR/assets/57001890/1f90acf9-8c1d-4359-aa40-fa8d53de4c78)

first part is reported in https://github.com/codescalers/CSHR/issues/382

**Comment by Mahmoud-Emad** [comment]
The feature should be added
