### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by rkhamis** [codescalersinternships/CSHR#4]
As a user I should be able to:

- [x] Apply for vacations
- [x] Apply for compensation days
  - [x] form should have:
        - [ ] reason for compensation
        - [ ] dates of work done that are being compensated
- [x] Request HR letters
   - [x]  form should have:
        - [x] addressee
        - [x] if salary should be mentioned (checkbox)
        - [x] #125
 - [ ] Request official docs from HR
   - [ ] form should have:
       - [ ] comments on what is needed

**Comment by Mahmoud-Emad** [comment]
@0oM4R 
see Hr Letters fields

![image](https://user-images.githubusercontent.com/57001890/189163299-43e1afd5-4888-4bf6-8d10-672ae3ce76bd.png)

**Comment by Mahmoud-Emad** [comment]
no in case I need an hr letter i can mention I want it on the exact date as I understand, is it?@rkhamis

**Comment by rkhamis** [comment]
in an HR letter, sometimes you want specific dates to be mentioned that the company approves you're on vacation during that period. those are the dates meant here

**Comment by 0oM4R** [comment]
As we discussed with Nayer, We need :

-  optional fields of start and end date, 
- mandatory field of date to receive the letter with 
can you please confirm that ? @rkhamis
