### ISSUE TITLE
Notifications disappear although the vacation is still pending 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#404]
when someone reporting to me apply for a vacation it appears in the notifications area, but suddenly it disappear although the vacation is still pending 
<img width="1435" alt="Screenshot 2024-04-24 at 11 39 02 AM" src="https://github.com/codescalers/CSHR/assets/14869003/336c4bfc-0aa7-43c3-b16a-93407a46fa7f">
<img width="1436" alt="Screenshot 2024-04-24 at 11 39 15 AM" src="https://github.com/codescalers/CSHR/assets/14869003/b1f76081-335c-4544-994f-fef17f396c6c">

**Comment by Mahmoud-Emad** [comment]
https://github.com/PaulGilmartin/django-pgpubsub

**Comment by Mahmoud-Emad** [comment]
The issue occurred because we only stored the notifications in Redis, which is a Memory Cache-based system. This is the reason why records are lost after a while.
