### ISSUE TITLE
add reporting to 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#410]
can we add reporting to in the profile page 
<img width="1229" alt="Screenshot 2024-04-30 at 3 31 00 PM" src="https://github.com/codescalers/CSHR/assets/14869003/6585867c-dc61-4f56-9865-27abcb160803">

**Comment by Mahmoud-Emad** [comment]
This should be done, please open this issue if you experience the same issue again.
