### ISSUE TITLE
Role to appear on the profile page 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#420]
When you open the profile page of any user can we add the Role of this user, So you can know what is his role in the organization. 
<img width="1427" alt="Screenshot 2024-05-27 at 9 12 54 AM" src="https://github.com/codescalers/CSHR/assets/14869003/9464f7ab-612a-4c8b-9a0e-b830acdd7a9d">

**Comment by Mahmoud-Emad** [comment]
The Role is already there.

![image](https://github.com/codescalers/CSHR/assets/57001890/634bad07-e357-457b-9d6f-0e7fd5e0d2e8)
![image](https://github.com/codescalers/CSHR/assets/57001890/00543c57-3d39-4c00-8951-c0758ae51032)

**Comment by Mahmoud-Emad** [comment]
The Role is already there.

![image](https://github.com/codescalers/CSHR/assets/57001890/634bad07-e357-457b-9d6f-0e7fd5e0d2e8)
![image](https://github.com/codescalers/CSHR/assets/57001890/00543c57-3d39-4c00-8951-c0758ae51032)
