### ISSUE TITLE
Requests are not shown in the notification section

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#421]
When a user apply for a vacation, it doesn't show in the notification section of the team lead (reporting to user) 
so the vacations are still pending on the calendar 
Below is an example of a vacation request from Zainab but it does not appear on the notification of Hanafi 
<img width="1428" alt="Screenshot 2024-05-27 at 10 17 58 AM" src="https://github.com/codescalers/CSHR/assets/14869003/13e38d6c-3f4b-4c31-a503-02c2035ee002">
![telegram-cloud-photo-size-4-5954109705452371647-y](https://github.com/codescalers/CSHR/assets/14869003/8939b18a-8828-4594-a802-0c89c3acd1da)

**Comment by Mahmoud-Emad** [comment]
Please research the Postgres pub-sub
