### ISSUE TITLE
The requested days are not shown while approving the request

### ISSUE THREAD

**Issue by AhmedHanafy725** [codescalersinternships/CSHR#423]
### Description

I can't see if it's a day or half-day

![image](https://github.com/codescalers/CSHR/assets/41957921/8cdd7497-a39f-4a14-a61c-a4679e8d1f5b)

**Comment by Mahmoud-Emad** [comment]
It wasn't 1 day, it was only 2 hours 
![image](https://github.com/user-attachments/assets/ded112cd-49e4-4ad6-ba3b-faffb44a92c9)

**Comment by zaelgohary** [comment]
> It wasn't 1 day, it was only 2 hours ![image](https://private-user-images.githubusercontent.com/57001890/349960506-ded112cd-49e4-4ad6-ba3b-faffb44a92c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDg5ODQsIm5iZiI6MTcyMTMwODY4NCwicGF0aCI6Ii81NzAwMTg5MC8zNDk5NjA1MDYtZGVkMTEyY2QtNDllNC00YWQ2LWJhM2ItZmFmZmI0NGE5MmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzMTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMWMwYmRiZTk1ZTViYWEwODg3YTI0ZjJjNjE1ODM2ZmRlNTA2MGEwN2YxZjQ0ZWEwYThjMWY4MzliMWJiOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2WutdAExQ2I5pTyRiY6WJGZzRa5rz-WaVopyxJC5iHI)

As per my conversation with @AhmedHanafy725 we agreed to keep the requested days to be as it is and change the from & to fields to include the hours.
