### ISSUE TITLE
leave summary page

### ISSUE THREAD

**Issue by 0oM4R** [codescalersinternships/CSHR#424]
### Description

to make it easier to check my leave history, we need a page that may do like this page in the old odoo system 
https://erp.codescalers.com/web?#page=0&limit=80&view_type=list&model=hr.holidays&action=409

**Comment by Nayer-Sobhy** [comment]
Mahmoud is already working on it in a different issue https://github.com/codescalers/CSHR/issues/433 that I created before actually seeing this one. 
So will close this one
