### ISSUE TITLE
added public holidays as admin yesterday to Mauritus office, today was not displayed

### ISSUE THREAD

**Issue by Karoline888** [codescalersinternships/CSHR#429]
I logged in as a Admin of Mauritius office yesterday and added all Public Holidays
Today when I logged in and clicked on dashboard it looked like I never did it. 
Screenshot
![image](https://github.com/codescalers/CSHR/assets/64146783/bde2e7d5-6aa2-49fd-8acc-7140ee241f0a)

I added again the details and "set balance"
![image](https://github.com/codescalers/CSHR/assets/64146783/120d1ce6-67e0-4cb0-bb0b-bf67d30842fd)
Alters bottom right says "Given token not valid for any token type"

**Comment by Karoline888** [comment]
I will observe if it's the same tomorrow :)

**Comment by Mahmoud-Emad** [comment]
Could be related to 

https://github.com/codescalers/CSHR/issues/425 
https://github.com/codescalers/CSHR/issues/431

**Comment by Karoline888** [comment]
indeed, my issue got resolved when I re-log in as admin. 
The public holidays are displayed and set as balance.
I guess we can close that ticket as it is indeed related to #431 maybe #425
