### ISSUE TITLE
Vacation balance calculation when adding a new user 

### ISSUE THREAD

**Issue by Nayer-Sobhy** [codescalersinternships/CSHR#432]
System is calculating the vacation balance based on the creation of the user but the system should calculate the balance based on the joining date not the adding user to the system date

**Comment by Mahmoud-Emad** [comment]
The `joining_at` date indicates when a user officially joined the company, whereas the `created_at` date marks when the user was initially added to the system.

Upon reflection, it's clear that calculating the balance based on either the `created_at` or `joining_at` dates is not appropriate. Instead, we should introduce an additional field to the system to denote whether the user is a newly joined user or an existing user.

For new users, the system will trigger the calculator service to determine their initial balance based on the month of joining. For existing users, administrators might need to manually set the balance during the user creation process.
