### ISSUE TITLE
create CRUD endpoints for Office, and evaluations

### ISSUE THREAD

**Issue by 0oM4R** [codescalersinternships/CSHR#46]
1. Create the following endpoints for Office, evaluations, and skills models 
> - Post
> - Get_all
> - Get
> - Update
> - delete
2. create unit tests for each endpoint
##### On branch : [Development_crud_endpoints_46](https://github.com/codescalersinternships/CSHR/tree/Development_crud_endpoints_46)

**Comment by 0oM4R** [comment]
for Office permissions point:

- Admin, superuser, and user can use `get` methods.
- Admin and superuser can `update` method.
- Admin only can `post` and `delete`

**Comment by 0oM4R** [comment]
for evaluations permissions point:

- user can use `get` method _only for his/her own evaluation_.
- Admin and superuser can `get`, `update`, and `post` methods.
- Admin only can use the `delete` method.

**Comment by Mahmoud-Emad** [comment]
@0oM4R 
The admin also can add users in the exacting office.

**Comment by 0oM4R** [comment]
> @0oM4R The admin also can add users in the exacting office.

@Mahmoud-Emad  I think this point belongs to modifying the user's data in the **User** view, right?

**Comment by Mahmoud-Emad** [comment]
@0oM4R 
1- Yes, this depends on the user, so as @aliasaddik said it is already implemented when the admin will register a new user and add him/her to an office.

2- Anyone can view the evaluation links.

**Comment by Mahmoud-Emad** [comment]
Implemnted!
