### ISSUE TITLE
Use the status of the request while creating instead of the current status

### ISSUE THREAD

**Issue by AhmedHanafy725** [codescalersinternships/CSHR#477]
I think it's confusing to use the current status as it might be changed after some changes.
for example
this is an approval notification but I have requested to cancel the request after. 
I'd like to see it `approved` instead of `requested to cancel`

![image](https://github.com/user-attachments/assets/11ba698d-502c-4876-b212-2872ef752448)

**Comment by zaelgohary** [comment]
As agreed with @AhmedHanafy725 , I removed the status from the toolbar, notifications & notification details as it might be confusing to the user.
