### ISSUE TITLE
Add validation for the meeting link

### ISSUE THREAD

**Issue by AhmedHanafy725** [codescalersinternships/CSHR#478]
it should have url validation

![image](https://github.com/user-attachments/assets/7e0fe7dc-1b25-4d65-88ba-980b147932bb)

**Comment by Mahmoud-Emad** [comment]
![image](https://github.com/user-attachments/assets/64fb26fe-dc65-47dc-b154-b5a504dbef64)

![image](https://github.com/user-attachments/assets/9e31c2f0-bc15-42c5-a3e3-dacf403ae21a)
