### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by rkhamis** [codescalersinternships/CSHR#7]
As a supervisor, I expect to be reminded when:
 -  [x] half of the probation period
 -  [x] end of probation period for each new hire
 -  [ ] quarterly evaultaions
 

I also expect a link to the appropriate form to be sent along the reminder

**Comment by Mahmoud-Emad** [comment]
@andrew-nassef 
@mhmdhelmy28 
Guys, we need one more celery task that runs for every quarter evaluation, implemented?
